cmd: "sh .scripts/deploy.sh"
name: "RCLC_Classic:deploy"
args:
   - "-c"
   - "{FILE_ACTIVE_PATH}"

errorMatch:
   - <ERROR>(?<message>.+)
warningMatch:
   - <WARNING>(?<message>.+)

targets:
   Release:
      cmd: ".scripts/build.sh"
      name: "RCLC_Classic:Release"
      sh: false
